# Generated by Django 4.2.4 on 2023-08-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_todo_description_todo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
